# Generated by Django 3.2.17 on 2023-02-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Your Name')),
                ('email', models.EmailField(max_length=50, verbose_name='Your Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Your Phone')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('people', models.CharField(max_length=3, verbose_name='# of People')),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
