# Generated by Django 3.2.17 on 2023-02-07 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
