# Generated by Django 3.2.17 on 2023-02-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20230208_1107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Reservation',
        ),
        migrations.AlterField(
            model_name='myrestaurantuser',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='myrestaurantuser',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='myrestaurantuser',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
    ]
