# Generated by Django 3.2.17 on 2023-02-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20230208_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='bookings',
            new_name='Guest',
        ),
    ]
