# Generated by Django 3.2.17 on 2023-02-09 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20230208_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bookings',
            new_name='guest',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='web',
        ),
        migrations.AlterField(
            model_name='book',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.branch'),
        ),
    ]
