# Generated by Django 3.2.17 on 2023-02-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20230209_0915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
