# Generated by Django 3.2.17 on 2023-02-09 10:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Your Name')),
                ('phone', models.CharField(max_length=50, verbose_name='Your Phone')),
                ('book_date', models.DateTimeField(default=datetime.datetime.now)),
                ('people', models.CharField(max_length=3, verbose_name='# of People')),
                ('message', models.TextField(blank=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.branch')),
                ('guest', models.ManyToManyField(blank=True, to='book.MyRestaurantUser')),
            ],
        ),
    ]
