# Generated by Django 3.2.17 on 2023-02-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_branch_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Guest Name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='people',
            field=models.CharField(max_length=3, verbose_name='# of Guest'),
        ),
        migrations.AlterField(
            model_name='book',
            name='phone',
            field=models.CharField(max_length=50, unique=True, verbose_name='Guest Phone'),
        ),
        migrations.AlterField(
            model_name='myrestaurantuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Email'),
        ),
    ]
