# Generated by Django 3.2.17 on 2023-02-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_myrestaurantuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrestaurantuser',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='Email'),
        ),
    ]
