# Generated by Django 3.2.17 on 2023-02-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_auto_20230218_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='guest',
            new_name='myrestaurantuser',
        ),
    ]
