# Generated by Django 3.2.17 on 2023-02-22 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_auto_20230219_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='branch',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
