# Generated by Django 3.2.17 on 2023-02-22 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
