# Generated by Django 3.2.18 on 2023-02-24 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0023_delete_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='myrestaurantuser',
        ),
        migrations.AddField(
            model_name='book',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MyRestaurantUser',
        ),
    ]
