# Generated by Django 3.2.18 on 2023-02-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_foods_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
